### ISSUE TITLE
Organize script

### ISSUE THREAD

**Issue by MobaLinux** [YahavP/lamp-automation#12]
Your script is unreadable because of the functions is not organized according to A - M - P

**Comment by tom-ha** [comment]
1. man grammar
2. the script is readable and organized

please close this issue there is nothing to fix here.

**Comment by MobaLinux** [comment]
okay good to know that your an English teacher ...
Never mind I won't get dragged into this discussion i'll just speak with the author directly ... Thanks tom ..
